In [2]:
import torch
import numpy as np

## 建立張量

In [3]:
# 0維 Tensor (純量scalar)
t0 = torch.tensor(1 , dtype=torch.int16)
print(t0.shape)

t0

torch.Size([])


tensor(1, dtype=torch.int16)

In [4]:
t0_t = torch.tensor(1 , dtype = torch.int16)

print(bool(t0_t.shape))
if not t0_t.shape:
  print('torch.Size([0])')

t0_t

False
torch.Size([0])


tensor(1, dtype=torch.int16)

因為純量的Tensor.shape輸出為空值

我用boolean驗證為False

使用偵測讓其輸出為torch.shape([0])

In [5]:
# 1維 Tensor (vector向量)
t1 = torch.tensor([1 , 2 , 3] , dtype = torch.float32)
print(t1.shape)
t1

torch.Size([3])


tensor([1., 2., 3.])

In [6]:
# 2維 Tensor (matrix矩陣)
t2 = torch.tensor([[1., 2 , 3] , [4 , 5 , 6]])
print(t2.shape)
t2

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

其中一值具有浮點數,就會使矩陣所有值都是浮點數

In [7]:
t2_t = torch.tensor([[1, 2, 3] , [4, 5, 6]] , dtype = torch.float32)
print(t2_t.shape)
t2_t

torch.Size([2, 3])


tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
# 3維 Tensor (n-dimensional array) 多維數組
t3 = torch.tensor([[[1 , 2], [3 , 4], [5 , 6]],[[7 , 8], [9 , 10], [11 , 12]]])
print(t3.shape)
t3

torch.Size([2, 3, 2])


tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

### 其他建立張量的方式

In [9]:
# tensor.randn : 平均值為0 , 標準差為1的常態分佈中 , 抽樣元素給定其形狀
tensor_randn_t3 = torch.randn((2 , 3 , 5))
print(tensor_randn_t3.shape)
tensor_randn_t3

torch.Size([2, 3, 5])


tensor([[[-0.9179, -0.8376,  0.0158,  1.4734, -0.4794],
         [-0.6742,  0.8687, -0.1271,  0.2634,  1.6003],
         [-0.2616, -0.1778,  1.1160,  0.6679, -0.7934]],

        [[ 0.1032, -0.1241,  0.6944,  0.7901, -1.2500],
         [ 2.1907, -0.6558, -1.2148, -0.1114,  0.6117],
         [ 0.6977, -0.9122, -1.1216,  0.1756, -0.0050]]])

In [10]:
# torch.randint : 給定上下界(預設下界為0)中抽樣"整數"元素組成給定形狀的張量
torch_randint_t2 = torch.randint(low = 0 , high = 10 , size = (3,2))
print(torch_randint_t2.shape)
torch_randint_t2

torch.Size([3, 2])


tensor([[5, 9],
        [8, 6],
        [9, 5]])

In [11]:
# torch.ones : 給定其形狀 , 元素全是1的張量
torch_ones_t2 = torch.ones((2,3))
print(torch_ones_t2.shape)
torch_ones_t2

torch.Size([2, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
# torch.ones_like : 產生與給定張量相同形狀 , 但元素全為1組成
torch_ones_like_tx = torch.ones_like(tensor_randn_t3)
print(torch_ones_like_tx.shape)
torch_ones_like_tx

torch.Size([2, 3, 5])


tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

## 張量與陣列的轉換

In [13]:
# 產生numpy ndarray
ndarray_x = np.array([[1., 2] , [3 , 4]])
print(ndarray_x.shape)
ndarray_x

(2, 2)


array([[1., 2.],
       [3., 4.]])

In [14]:
# 由 numpy ndarray 產生 pytorch tensor
tensor_y = torch.from_numpy(ndarray_x)
tensor_y_t = torch.tensor(ndarray_x) #也可以達到
print(tensor_y.shape)
print(tensor_y_t.shape)
print(tensor_y)
print(tensor_y_t)

torch.Size([2, 2])
torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [15]:
ndarray_x.dtype , tensor_y.dtype

(dtype('float64'), torch.float64)

In [16]:
# 將tensor轉換為array

transfer_z = tensor_y.numpy()
print(transfer_z.shape)
transfer_z

(2, 2)


array([[1., 2.],
       [3., 4.]])

In [18]:
#建立Torch
a = torch.randn((2 , 3))
b = torch.randn(3)

print(a.shape , b.shape)

a , b

torch.Size([2, 3]) torch.Size([3])


(tensor([[ 0.5998,  1.3174, -2.1760],
         [ 2.7388,  0.1165,  1.2168]]),
 tensor([ 0.7977,  0.5466, -0.1019]))

In [19]:
#相加
t_add1 = a + b
t_add2 = torch.add(a , b)
print(t_add1.shape , t_add2.shape)
t_add1 , t_add2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[ 1.3975,  1.8640, -2.2779],
         [ 3.5365,  0.6632,  1.1149]]),
 tensor([[ 1.3975,  1.8640, -2.2779],
         [ 3.5365,  0.6632,  1.1149]]))

In [20]:
#相減
t_sub1 = a - b
t_sub2 = torch.sub(a , b)
print(t_sub1.shape , t_sub2.shape)
t_sub1 , t_sub2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[-0.1980,  0.7707, -2.0741],
         [ 1.9411, -0.4301,  1.3187]]),
 tensor([[-0.1980,  0.7707, -2.0741],
         [ 1.9411, -0.4301,  1.3187]]))

In [22]:
# 相除
t_div1 = a / b
t_div2 = torch.div(a , b)
print(t_div1.shape , t_div2.shape)
t_div1 , t_div2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[  0.7518,   2.4100,  21.3547],
         [  3.4332,   0.2132, -11.9416]]),
 tensor([[  0.7518,   2.4100,  21.3547],
         [  3.4332,   0.2132, -11.9416]]))

In [23]:
# 相乘
t_mul1 = a * b
t_mul2 = torch.mul(a , b)
print(t_mul1.shape , t_mul2.shape)
t_mul1 , t_mul2

torch.Size([2, 3]) torch.Size([2, 3])


(tensor([[ 0.4785,  0.7201,  0.2217],
         [ 2.1848,  0.0637, -0.1240]]),
 tensor([[ 0.4785,  0.7201,  0.2217],
         [ 2.1848,  0.0637, -0.1240]]))

上方部分是元素對元素(element-wise)的相乘，而非一般的矩陣相乘

In [24]:
#張量矩陣相乘
c = torch.randn((2 , 3))
d = torch.randn((3 , 4))

t_matmul1 = c.mm(d)
t_matmul2 = torch.mm(c , d)
t_matmul3 = torch.matmul(c , d)
t_matmul4 = c @ d

print(t_matmul1.shape, t_matmul2.shape , t_matmul3.shape , t_matmul4.shape)

torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4])


我們針對Shape進行操作也十分重要
先改變維度再進行矩陣相乘(ex : 2 x 3 > 3 x 2)

In [26]:
#張量形狀操作
a = torch.tensor([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])

print(a.shape)
print(a)

torch.Size([2, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])


In [27]:
b = a.reshape(2 , 6)
c = a.view(2 , 6)
d = a.reshape(2 , -1)
print(b.shape , c.shape , d.shape)
b , c ,d

torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])


(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]))

permute 給定順序 範例的(0,2,1)代表順序將轉換成(2(原先第0維) , 3(原先第2維) , 2(原先第1維))

transpose 給定的維度對調 (1,2) 表示3(第1維)與2(第2維)對調

In [28]:
#調換Tensor維度
e = a.permute((0, 2, 1))
f = a.transpose(1 , 2)
print(e.shape , f.shape)
e , f

torch.Size([2, 3, 2]) torch.Size([2, 3, 2])


(tensor([[[ 1,  4],
          [ 2,  5],
          [ 3,  6]],
 
         [[ 7, 10],
          [ 8, 11],
          [ 9, 12]]]),
 tensor([[[ 1,  4],
          [ 2,  5],
          [ 3,  6]],
 
         [[ 7, 10],
          [ 8, 11],
          [ 9, 12]]]))

unsqueeze 再給定位置增加維度

squeeze 給定維度元素數量為1 則壓縮給定位置(若無給定則所有維度為1的位置都壓縮)

In [31]:
#增加維度
g = torch.unsqueeze(a , dim = 1)
h = torch.squeeze(g)
print(g.shape , h.shape)
g , h

torch.Size([2, 1, 2, 3]) torch.Size([2, 2, 3])


(tensor([[[[ 1,  2,  3],
           [ 4,  5,  6]]],
 
 
         [[[ 7,  8,  9],
           [10, 11, 12]]]]),
 tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]))